# Generated by Django 3.2.16 on 2024-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
